// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.test.main {
    exports com.mastfrog.testmain;
    exports com.mastfrog.testmain.suites;

    // derived from com.google.guava/guava-31.1-jre in com/google/guava/guava/31.1-jre/guava-31.1-jre.pom
    requires com.google.common;

    // Sibling com.mastfrog/annotation-processors-3.0.0-dev:compile
    requires com.mastfrog.annotation.processors;

    // Sibling com.mastfrog/annotation-tools-3.0.0-dev
    requires com.mastfrog.annotation.tools;

    // Sibling com.mastfrog/giulius-3.0.0-dev
    requires com.mastfrog.giulius;

    // Sibling com.mastfrog/giulius-settings-3.0.0-dev
    requires com.mastfrog.giulius.settings;

    // Inferred from source scan
    requires com.mastfrog.streams;
    requires java.compiler;
    requires java.desktop;

    // Inferred from test-source-scan

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires  junit;
    provides javax.annotation.processing.Processor with
       com.mastfrog.testmain.suites.SuitesProcessor;

}
