open module com.mastfrog.test.main {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.testmain;
    exports com.mastfrog.testmain.suites;

    // derived from com.google.guava/guava-31.1-jre in com/google/guava/guava/31.1-jre/guava-31.1-jre.pom
    requires transitive com.google.guava.guava;
    requires transitive com.mastfrog.annotation.processors;
    requires transitive com.mastfrog.annotation.tools;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.giulius.settings;
    requires java.compiler;
    requires java.desktop;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
