// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.video {
    exports com.mastfrog.video;

    // Sibling com.mastfrog/giulius-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.giulius;

    // Sibling com.mastfrog/giulius-tests-3.0.0-dev
    requires com.mastfrog.giulius.tests;
    requires com.mastfrog.giulius.settings;

    // Inferred from source scan

    // Sibling com.mastfrog/util-time-3.0.0-dev
    requires com.mastfrog.time;
    requires java.logging;

    // Inferred from test-source-scan
    requires junit;
}
