open module com.mastfrog.video {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.video;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.util.time;
    requires java.logging;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
