open module com.mastfrog.selenium {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.selenium;

    // derived from com.assertthat/selenium-shutterbug-1.6 in com/assertthat/selenium-shutterbug/1.6/selenium-shutterbug-1.6.pom
    requires transitive com.assertthat.selenium.shutterbug;
    requires transitive com.mastfrog.embedded.jetty;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.giulius.annotation.processors;
    requires transitive com.mastfrog.giulius.annotations;
    requires transitive com.mastfrog.giulius.tests;

    // derived from commons-codec/commons-codec-1.15 in commons-codec/commons-codec/1.15/commons-codec-1.15.pom
    requires transitive commons.codec.commons.codec;
    requires java.desktop;
    requires java.logging;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

    // derived from org.eclipse.jetty/jetty-client-9.4.44.v20210927 in org/eclipse/jetty/jetty-client/9.4.44.v20210927/jetty-client-9.4.44.v20210927.pom
    requires transitive org.eclipse.jetty.jetty.client;

    // derived from org.eclipse.jetty/jetty-util-9.4.44.v20210927 in org/eclipse/jetty/jetty-util/9.4.44.v20210927/jetty-util-9.4.44.v20210927.pom
    requires transitive org.eclipse.jetty.jetty.util;

    // derived from org.eclipse.jetty.websocket/websocket-api-9.4.44.v20210927 in org/eclipse/jetty/websocket/websocket-api/9.4.44.v20210927/websocket-api-9.4.44.v20210927.pom
    requires transitive org.eclipse.jetty.websocket.websocket.api;

    // derived from org.eclipse.jetty.websocket/websocket-client-9.4.44.v20210927 in org/eclipse/jetty/websocket/websocket-client/9.4.44.v20210927/websocket-client-9.4.44.v20210927.pom
    requires transitive org.eclipse.jetty.websocket.websocket.client;

    // derived from org.seleniumhq.selenium/selenium-java-4.1.4 in org/seleniumhq/selenium/selenium-java/4.1.4/selenium-java-4.1.4.pom
    requires transitive org.seleniumhq.selenium.java;

}
