// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.selenium {
    exports com.mastfrog.selenium;

    // Inferred from source scan
    requires com.mastfrog.collections;

    // Sibling com.mastfrog/giulius-3.0.0-dev
    requires com.mastfrog.giulius;

    // Transitive detected by source scan
    requires com.mastfrog.giulius.settings;

    // Sibling com.mastfrog/giulius-tests-3.0.0-dev
    requires com.mastfrog.giulius.tests;

    // Inferred from source scan
    requires com.mastfrog.preconditions;
    requires java.desktop;
    requires java.logging;
    
//    requires org.openqa.selenium.support.ui;
    
    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires junit;
    requires hamcrest.core;

//    requires transitive org.seleniumhq.selenium.api;
    // derived from org.seleniumhq.selenium/selenium-java-4.1.4 in org/seleniumhq/selenium/selenium-java/4.1.4/selenium-java-4.1.4.pom
    requires transitive org.seleniumhq.selenium.java;
//    requires transitive org.seleniumhq.selenium.http;
    requires transitive org.seleniumhq.selenium.support;
    requires transitive org.seleniumhq.selenium.chrome_driver;
    requires transitive org.seleniumhq.selenium.firefox_driver;
    requires transitive org.seleniumhq.selenium.ie_driver;
    requires transitive org.seleniumhq.selenium.http;
    requires htmlunit.driver;

    // derived from com.assertthat/selenium-shutterbug-1.6 in com/assertthat/selenium-shutterbug/1.6/selenium-shutterbug-1.6.pom
    requires selenium.shutterbug;

}
